
# nacos 配置中心
server:
  port: 3377

spring:
  profiles:
    active: dev # 表示开发环境

  application:
    name: nacos-config
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.168.60:8848    # nacos 服务注册中心地址
      config:
        server-addr: 192.168.168.60:8848    # nacos 作为配置中心地址
        file-extension: yaml
    #        group: DEV_GROUP    # 指定配置文件分组 GROUP
    #        namespace: nacos-config-dev-01

    # ${spring.application.name}-${spring.profile.active}-${spring.cloud.nacos.config-file-extension}
