server:
  port: 9101

spring:
  application:
    name: nacos-consumer-9101
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.168.60:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'